#!/usr/bin/env bash
# configuring an inginx server to  listen on port 80

#create a symbolic link (-s option) between the nginx configuration file 
#and the enabled sites directory
ln -sf /etc/nginx/sites-available/defaukt /etc/nginx/sites-enabled/default
#restart nginx 
srvice nginx start
#terminates the first nginx process ID 
kill "$(pgrep 'nginx' | head -1)"
