#!/usr/bin/env bash
#Commnds for installing nginx on web server
sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World" | tee /var/www/html/index.html
#Testing our nginx 
sudo nginx -t

sudo service nginx reload
